---
version: "0.1"
services:
  wspr:
    image: wspr:latest
    container_name: wspr
    network_mode: host
    environment:
      - TELOXIDE_TOKEN=YOUR_TG_TOKEN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /media:/config
      - /media:/multimedia
    restart: unless-stopped